export interface Tool {
  id: string
  name: string
  description: string
  link: string
  category: string
  type: string
  useCase?: string
  industry?: string
  featured: boolean
  setting?: string
  affiliateLink?: string
  educationalValue?: string
}

// Complete data from the provided CSV file
export const tools: Tool[] = [
  // === 2026 TOP AI TOOLS ===
  // AI Assistants & Chatbots
  {
    id: "302",
    name: "ChatGPT (GPT-5.2)",
    description: "All-around best AI productivity tool with deep reasoning, long-term memory, and autonomous task execution",
    link: "https://chat.openai.com",
    category: "Productivity",
    type: "AI Assistant",
    featured: true,
  },
  {
    id: "303",
    name: "Claude (Opus 4.1)",
    description: "Complex reasoning, long-context analysis, and safe enterprise deployment with natural writing",
    link: "https://claude.ai",
    category: "Productivity",
    type: "AI Assistant",
    featured: true,
  },
  {
    id: "304",
    name: "Google Gemini 3.0 Pro",
    description: "Powerful multimodal AI with massive context windows (2M tokens) and deep Google Workspace integration",
    link: "https://gemini.google.com",
    category: "Productivity",
    type: "AI Assistant",
    featured: true,
  },
  {
    id: "305",
    name: "Microsoft Copilot Wave 2",
    description: "Productivity powerhouse in Microsoft 365 ecosystem with Copilot Pages for collaborative AI",
    link: "https://copilot.microsoft.com",
    category: "Productivity",
    type: "AI Assistant",
    featured: true,
  },
  {
    id: "306",
    name: "Perplexity",
    description: "Real-time research and fact-checking with cited sources, includes Comet browser",
    link: "https://perplexity.ai",
    category: "Research & Analysis",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "307",
    name: "Grok 4 (xAI)",
    description: "Advanced reasoning and real-time search integrated into X (Twitter)",
    link: "https://x.ai",
    category: "Productivity",
    type: "AI Assistant",
    featured: false,
  },
  {
    id: "308",
    name: "DeepSeek",
    description: "Open-source model with excellent technical reasoning and cost-effectiveness",
    link: "https://deepseek.com",
    category: "Programming",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "309",
    name: "HuggingChat",
    description: "Free community-driven platform using open-source models with privacy focus",
    link: "https://huggingface.co/chat",
    category: "Productivity",
    type: "AI Assistant",
    featured: false,
  },
  // Coding & Development
  {
    id: "310",
    name: "Cursor",
    description: "AI-native IDE with deep codebase understanding, Composer mode, and multi-file editing",
    link: "https://cursor.sh",
    category: "Programming",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "311",
    name: "GitHub Copilot",
    description: "Industry standard AI coding assistant with Workspace, multi-model support, and cloud agents",
    link: "https://github.com/features/copilot",
    category: "Programming",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "312",
    name: "v0 by Vercel",
    description: "UI component generation with sandbox runtime, Git integration, and Next.js deployment",
    link: "https://v0.dev",
    category: "Programming",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "313",
    name: "Replit Agent",
    description: "All-in-one development platform with autonomous app building and instant deployment",
    link: "https://replit.com",
    category: "Programming",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "314",
    name: "Lovable AI",
    description: "Turns design concepts into fully functioning web apps without coding",
    link: "https://lovable.ai",
    category: "Programming",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "315",
    name: "Aider",
    description: "Terminal-based coding assistant with Git integration for developers",
    link: "https://aider.chat",
    category: "Programming",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "316",
    name: "Continue",
    description: "AI-assisted coding directly within IDEs (VS Code, JetBrains)",
    link: "https://continue.dev",
    category: "Programming",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "317",
    name: "Tabby",
    description: "Self-hosted coding assistant emphasizing data privacy",
    link: "https://tabby.tabbyml.com",
    category: "Programming",
    type: "AI Tool",
    featured: false,
  },
  // Image Generation
  {
    id: "318",
    name: "Midjourney v7",
    description: "High-fidelity image generation with painterly aesthetic, industry-leading visual quality",
    link: "https://midjourney.com",
    category: "DALL-E",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "319",
    name: "DALL-E 3",
    description: "High-quality imaginative visuals with ChatGPT integration and improved prompt understanding",
    link: "https://openai.com/dall-e-3",
    category: "DALL-E",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "320",
    name: "Adobe Firefly 4",
    description: "Production-ready vectors and brand assets integrated into Adobe Creative Cloud",
    link: "https://firefly.adobe.com",
    category: "DALL-E",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "321",
    name: "Nano Banana Pro (Gemini)",
    description: "Photorealism, accurate text generation, and consistency for various edits",
    link: "https://gemini.google.com",
    category: "DALL-E",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "322",
    name: "Ideogram",
    description: "Perfect text rendering within images with Magic Prompt for enhanced results",
    link: "https://ideogram.ai",
    category: "DALL-E",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "323",
    name: "Stable Diffusion XL 2.0",
    description: "Custom styles and full control over image generation",
    link: "https://stability.ai",
    category: "DALL-E",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "324",
    name: "Leonardo.ai",
    description: "AI art generator with consistent character creation and style control",
    link: "https://leonardo.ai",
    category: "DALL-E",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "325",
    name: "Playground AI",
    description: "Free AI image generator with advanced editing capabilities",
    link: "https://playground.com",
    category: "DALL-E",
    type: "AI Tool",
    featured: false,
  },
  // Video Generation
  {
    id: "326",
    name: "Google Veo 3.1",
    description: "Creative AI videos from text with realistic physics and camera movements",
    link: "https://deepmind.google/technologies/veo",
    category: "Video",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "327",
    name: "OpenAI Sora 2",
    description: "Realistic and imaginative video scenes with synchronized audio generation",
    link: "https://openai.com/sora",
    category: "Video",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "328",
    name: "Runway Gen-4",
    description: "Video magic wand with cinematic quality, consistent styles, and advanced editing",
    link: "https://runwayml.com",
    category: "Video",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "329",
    name: "Kling AI 2.6",
    description: "Strong physics and realistic 3D motion with superior consistency",
    link: "https://klingai.com",
    category: "Video",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "330",
    name: "HeyGen",
    description: "Best lip-sync quality with Video Translate feature for multilingual content",
    link: "https://heygen.com",
    category: "Video",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "331",
    name: "Synthesia",
    description: "Realistic AI avatar videos for training, presentations, and marketing",
    link: "https://synthesia.io",
    category: "Video",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "332",
    name: "Descript",
    description: "Edit video by editing text with automatic transcription",
    link: "https://descript.com",
    category: "Video",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "333",
    name: "Invideo AI",
    description: "Full video generation and re-editing based on commands",
    link: "https://invideo.ai",
    category: "Video",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "334",
    name: "OpusClip",
    description: "Break down longer videos into shareable clips with captions",
    link: "https://opus.pro",
    category: "Video",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "335",
    name: "Pika Labs",
    description: "Text-to-video with creative effects and style transformations",
    link: "https://pika.art",
    category: "Video",
    type: "AI Tool",
    featured: false,
  },
  // Writing & Content
  {
    id: "336",
    name: "Jasper AI",
    description: "High-volume content creation with templates and research capabilities",
    link: "https://jasper.ai",
    category: "Writing",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "337",
    name: "Copy.ai",
    description: "Marketing and content creation with brand voice consistency",
    link: "https://copy.ai",
    category: "Writing",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "338",
    name: "Surfer SEO",
    description: "SEO-optimized content with integrated research and optimization",
    link: "https://surferseo.com",
    category: "Writing",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "339",
    name: "Grammarly",
    description: "Grammar, style checking with tone detection and generative text",
    link: "https://grammarly.com",
    category: "Writing",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "340",
    name: "QuillBot",
    description: "Paraphrasing and summarization for improved content flow",
    link: "https://quillbot.com",
    category: "Writing",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "341",
    name: "Wordtune",
    description: "Sentence rewriting and alternative wording suggestions",
    link: "https://wordtune.com",
    category: "Writing",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "342",
    name: "Rytr",
    description: "Popular AI writing software for all-round text generation",
    link: "https://rytr.me",
    category: "Writing",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "343",
    name: "Sudowrite",
    description: "AI specifically designed for creative writing and storytelling",
    link: "https://sudowrite.com",
    category: "Writing",
    type: "AI Tool",
    featured: false,
  },
  // Design & UI/UX
  {
    id: "344",
    name: "Figma AI v2",
    description: "Layout assistance and design system maintenance within Figma",
    link: "https://figma.com",
    category: "DALL-E",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "345",
    name: "Canva Magic Studio",
    description: "Generate presentations, social posts, and documents from prompts",
    link: "https://canva.com",
    category: "DALL-E",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "346",
    name: "UX Pilot",
    description: "Generate wireframes using existing components and design tokens",
    link: "https://uxpilot.ai",
    category: "DALL-E",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "347",
    name: "Khroma AI",
    description: "Learn color preferences to build custom palettes",
    link: "https://khroma.co",
    category: "DALL-E",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "348",
    name: "CorelDRAW Vision AI",
    description: "Print and vector precision design with AI assistance",
    link: "https://coreldraw.com",
    category: "DALL-E",
    type: "AI Tool",
    featured: false,
  },
  // Automation & Workflow
  {
    id: "349",
    name: "Zapier Central",
    description: "Connect 8000+ apps with AI Agents for complex multi-step workflows",
    link: "https://zapier.com",
    category: "Productivity",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "350",
    name: "n8n",
    description: "Open-source workflow automation with custom AI agents and self-hosting",
    link: "https://n8n.io",
    category: "Productivity",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "351",
    name: "Make (Integromat)",
    description: "Visual automation with AI Agents for complex data transformations",
    link: "https://make.com",
    category: "Productivity",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "352",
    name: "FlowHunt",
    description: "No-code AI agent building platform with multi-model support",
    link: "https://flowhunt.io",
    category: "Productivity",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "353",
    name: "CrewAI",
    description: "Open-source Python framework for multi-agent orchestration",
    link: "https://crewai.com",
    category: "Programming",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "354",
    name: "LangChain",
    description: "Framework for developing applications with large language models",
    link: "https://langchain.com",
    category: "Programming",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "355",
    name: "AutoGen (Microsoft)",
    description: "Open-source framework for multi-agent AI collaboration",
    link: "https://microsoft.github.io/autogen",
    category: "Programming",
    type: "AI Tool",
    featured: false,
  },
  // Research & Productivity
  {
    id: "356",
    name: "NotebookLM",
    description: "Grounded AI expert for documents with audio overviews and citations",
    link: "https://notebooklm.google.com",
    category: "Research & Analysis",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "357",
    name: "Motion",
    description: "AI scheduling tool that enhances productivity and time management",
    link: "https://usemotion.com",
    category: "Productivity",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "358",
    name: "Fireflies.ai",
    description: "Automate post-meeting workflows with transcription and note-taking",
    link: "https://fireflies.ai",
    category: "Productivity",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "359",
    name: "Notion AI",
    description: "AI integrated into flexible workspace for content, notes, and databases",
    link: "https://notion.so/product/ai",
    category: "Productivity",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "360",
    name: "Wisprflow",
    description: "Context-aware voice-to-text for emails, messages, and prompts",
    link: "https://wisprflow.ai",
    category: "Productivity",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "361",
    name: "Scouts (UTOI)",
    description: "Daily research scanning the internet for specific topics",
    link: "https://scouts.ai",
    category: "Research & Analysis",
    type: "AI Tool",
    featured: false,
  },
  // AI Agents Platforms
  {
    id: "362",
    name: "Microsoft Copilot Studio",
    description: "Design, deploy, and manage custom AI agents in Microsoft ecosystem",
    link: "https://microsoft.com/copilot/studio",
    category: "Business",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "363",
    name: "Google Vertex AI Agent Builder",
    description: "Build conversational AI agents with Google Cloud integration",
    link: "https://cloud.google.com/vertex-ai",
    category: "Business",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "364",
    name: "Lindy AI",
    description: "No-code AI agent for customer support and workflow automation",
    link: "https://lindy.ai",
    category: "Business",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "365",
    name: "Gumloop",
    description: "AI-first no-code automation blending Zapier and ChatGPT",
    link: "https://gumloop.com",
    category: "Productivity",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "366",
    name: "Stack AI",
    description: "Build and deploy AI agents for enterprise workflows",
    link: "https://stack-ai.com",
    category: "Business",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "367",
    name: "Botpress",
    description: "Open-source conversational AI platform for chatbots",
    link: "https://botpress.com",
    category: "Business",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "368",
    name: "Voiceflow",
    description: "Design, prototype, and launch conversational AI experiences",
    link: "https://voiceflow.com",
    category: "Business",
    type: "AI Tool",
    featured: false,
  },
  // Specialized Tools
  {
    id: "369",
    name: "Tray.ai",
    description: "Enterprise-grade platform for complex AI-driven workflows",
    link: "https://tray.ai",
    category: "Business",
    type: "Business",
    featured: false,
  },
  {
    id: "370",
    name: "Workato",
    description: "Enterprise automation with AI and robust governance features",
    link: "https://workato.com",
    category: "Business",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "371",
    name: "IBM Watson",
    description: "Enterprise AI for business intelligence and analytics",
    link: "https://ibm.com/watson",
    category: "Business",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "372",
    name: "OpenAI Operator",
    description: "AI agent browser automator for web tasks and research",
    link: "https://openai.com/operator",
    category: "Productivity",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "373",
    name: "Devin AI",
    description: "Autonomous AI software engineer for code generation",
    link: "https://devin.ai",
    category: "Programming",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "374",
    name: "AirOps",
    description: "AI workflows for marketing and sales teams",
    link: "https://airops.com",
    category: "Business",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "375",
    name: "Writer.com AI",
    description: "Proprietary LLMs for brand voice consistency in enterprises",
    link: "https://writer.com",
    category: "Writing",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "376",
    name: "Higgsfield",
    description: "AI video creation studio for professional content",
    link: "https://higgsfield.ai",
    category: "Video",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "377",
    name: "Magic Hour",
    description: "All-in-one AI creation platform for image, animation, and video",
    link: "https://magichour.ai",
    category: "Video",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "378",
    name: "Meta AI (LLaMA)",
    description: "Open-source models for custom AI applications and research",
    link: "https://ai.meta.com",
    category: "Programming",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "379",
    name: "Hugging Face Hub",
    description: "Marketplace of open-source AI models for customization",
    link: "https://huggingface.co",
    category: "Programming",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "380",
    name: "Imagen 3 (Google)",
    description: "Highly detailed image generation with flexible editing",
    link: "https://deepmind.google/technologies/imagen-3",
    category: "DALL-E",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "381",
    name: "Blue Willow",
    description: "Free AI image generator operating via Discord",
    link: "https://bluewillow.ai",
    category: "DALL-E",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "382",
    name: "Vellum AI",
    description: "Build and deploy production-ready AI applications",
    link: "https://vellum.ai",
    category: "Programming",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "383",
    name: "LTX Studio",
    description: "AI-powered video storytelling and production platform",
    link: "https://ltx.studio",
    category: "Video",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "384",
    name: "Replit Design",
    description: "AI website design that builds working applications from concepts",
    link: "https://replit.com/design",
    category: "Programming",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "385",
    name: "OpenHands",
    description: "Autonomous AI software engineer for code development",
    link: "https://openhands.ai",
    category: "Programming",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "386",
    name: "Goose AI",
    description: "Generate entire codebases from natural language descriptions",
    link: "https://goose.ai",
    category: "Programming",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "387",
    name: "Zep",
    description: "Memory layer for AI applications and chatbots",
    link: "https://getzep.com",
    category: "Programming",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "388",
    name: "Comet Browser (Perplexity)",
    description: "AI-powered browser with integrated research capabilities",
    link: "https://perplexity.ai/comet",
    category: "Productivity",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "389",
    name: "Magic Studio (Canva)",
    description: "AI design suite within Canva for automated creative work",
    link: "https://canva.com/magic-studio",
    category: "DALL-E",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "390",
    name: "GitHub Copilot Workspace",
    description: "Task-centric environment from Issue to Pull Request",
    link: "https://github.com/features/copilot-workspace",
    category: "Programming",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "391",
    name: "Visual Studio 2026 AI",
    description: "Enhanced coding with cloud agents and C++ editing tools",
    link: "https://visualstudio.microsoft.com",
    category: "Programming",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "392",
    name: "ChatGPT Canvas",
    description: "Collaborative writing and coding workspace in ChatGPT",
    link: "https://openai.com/canvas",
    category: "Productivity",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "393",
    name: "Typebot",
    description: "No-code chatbot builder with AI integration",
    link: "https://typebot.io",
    category: "Business",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "394",
    name: "Eesel AI",
    description: "AI assistant trained on your company's knowledge",
    link: "https://eesel.ai",
    category: "Business",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "395",
    name: "Librancy AI",
    description: "AI-powered research and document analysis platform",
    link: "https://librancy.ai",
    category: "Research & Analysis",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "396",
    name: "Builder.io",
    description: "Visual development platform with AI-powered design-to-code",
    link: "https://builder.io",
    category: "Programming",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "397",
    name: "Browse AI Tools",
    description: "Comprehensive directory of AI tools and platforms",
    link: "https://browse-ai.tools",
    category: "Research & Analysis",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "398",
    name: "Wavespeed AI",
    description: "AI automation for customer service and support",
    link: "https://wavespeed.ai",
    category: "Business",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "399",
    name: "Clipchamp",
    description: "Microsoft's video editor with AI-powered features",
    link: "https://clipchamp.com",
    category: "Video",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "400",
    name: "Futurepedia",
    description: "Largest AI tools directory with daily updates",
    link: "https://futurepedia.io",
    category: "Research & Analysis",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "401",
    name: "Appypie Automate",
    description: "No-code automation platform with AI integration",
    link: "https://appypieautomate.ai",
    category: "Productivity",
    type: "AI Tool",
    featured: false,
  },

  {
    id: "1",
    name: "Agent Builder Guide",
    description: "Guides beginners in building any AI agent with SDKs, Restack, MCP, and API integration",
    link: "https://chatgpt.com/g/g-6823d7ef9e388191bb15547171896084-agent-builder-guide",
    category: "Programming",
    type: "Custom GPT",
    setting: "GPT Store",
    featured: true,
    affiliateLink: "https://example.com/affiliate/agent-builder",
    educationalValue: "Learn the fundamentals of agentic workflows.",
  },
  {
    id: "2",
    name: "Chatbot Architect",
    description: "Builds structured chatbot instructions and guides step-by-step configuration on no-code platforms.",
    link: "https://chatgpt.com/g/g-6820f686c3608191819ebb80e57e990a-chatbot-architect",
    category: "Programming",
    type: "Custom GPT",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "3",
    name: "Poor Richard's GPT",
    description: "Provides quotes and insights from Poor Richard's Almanack",
    link: "https://chatgpt.com/g/g-681ee3be47a0819182590ec346cb304a-poor-richard-s-gpt",
    category: "Lifestyle",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "4",
    name: "Automation Architect",
    description: "Expert in Make, Zapier, n8n; builds custom automations step-by-step",
    link: "https://chatgpt.com/g/g-681e8b22123881919856dcbd09b1765c-automation-architect",
    category: "Productivity",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "5",
    name: "Course Builder Assistant",
    description: "Transforms course ideas or documents into structured outlines and full course content.",
    link: "https://chatgpt.com/g/g-68169561b7108191a2eee3758dace731-course-builder-assistant",
    category: "Productivity",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "6",
    name: "v0.dev Full Stack App Builder",
    description: "Delivers exactly 10 v0.dev prompts to build full stack app MVPs.",
    link: "https://chatgpt.com/g/g-681685f291a48191a687c6dac28f4412-v0-dev-full-stack-app-builder",
    category: "Programming",
    type: "Custom GPT",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "7",
    name: "Centralized Systems Assistant",
    description: "Assists systems teams with documentation, automation, troubleshooting, and programming tasks.",
    link: "https://chatgpt.com/g/g-68118b25ebd48191be50ecaa749812e5-centralized-systems-assistant",
    category: "Productivity",
    setting: "Private Link",
    featured: false,
  },
  {
    id: "8",
    name: "Custom GPT Builder Guide",
    description: "A calm, expert assistant guiding you step-by-step to design, customize, and refine your perfect GPT.",
    link: "https://chatgpt.com/g/g-681009c908b481919c03570bc6e4c7b2-custom-gpt-builder-guide",
    category: "Programming",
    type: "Custom GPT",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "9",
    name: "Compass GPT Builder",
    description: "Helps users build custom GPTs",
    link: "https://chatgpt.com/g/g-681004f42b9c819199877e2d765d3523-compass-gpt-builder",
    category: "Programming",
    type: "Custom GPT",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "10",
    name: "Custom GPT Guide",
    description: "A step-by-step tutorial guide for building custom GPTs.",
    link: "https://chatgpt.com/g/g-681003e70b4081919f5c7accc1096e21-custom-gpt-guide",
    category: "Programming",
    type: "Custom GPT",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "11",
    name: "Full Stack Copilot",
    description: "Scaffolds components from user prompts using React, Tailwind, shadcn/ui, and full-stack logic.",
    link: "https://chatgpt.com/g/g-681003e70b4081919f5c7accc1096e21-custom-gpt-guide",
    category: "Programming",
    type: "Custom GPT",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "12",
    name: "Jobs to be Done",
    description: "Transforms prompts and docs into AI-ready 'Jobs to Be Done' blueprints with guided flows.",
    link: "https://chatgpt.com/g/g-6802c7da3c688191875f67a5468d82e2-jobs-to-be-done",
    category: "Productivity",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "13",
    name: "Prayer Companion",
    description: "Transforms your worries into heartfelt, personalized prayers.",
    link: "https://chatgpt.com/g/g-67f897048ab881919b0d33912bd8481d-prayer-companion",
    category: "Lifestyle",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "14",
    name: "Chatbot Guide Bot (Using Voice Flow)",
    description: "Step-by-step chatbot builder using prompts and downloadable .vf files to help with (voiceflow, etc)",
    link: "https://chatgpt.com/g/g-67f68acfada0819194761d7dc2c8f7bc-chatbot-guide-bot-using-voice-flow",
    category: "Programming",
    type: "Custom GPT",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "15",
    name: "People For GPT",
    description: "Mobilizes action to defend democracy, equity, and justice with People For the American Way.",
    link: "https://chatgpt.com/g/g-67f425684708819190100be5b7052922-people-for-gpt",
    category: "Research & Analysis",
    setting: "Private Link",
    featured: false,
  },
  {
    id: "16",
    name: "Replit Builder",
    description: "Formats and refines prompts for efficient Replit project building",
    link: "https://chatgpt.com/g/g-67ebbfd9befc819187ed1174fd1d8289-replit-builder",
    category: "Programming",
    type: "Custom GPT",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "17",
    name: "PromptBuilder Architect V2",
    description: "Breaks down app ideas into modular prompts for lovable.dev, tailored by plan tier",
    link: "https://chatgpt.com/g/g-67ebbfd7c70c8191b0842c96d89af2ac-promptbuilder-architect-v2",
    category: "Programming",
    type: "Custom GPT",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "18",
    name: "PromptBuilder Architect",
    description: "Creates modular prompt sets for v0.dev, Cursor, and Replit apps with UI, backend, and deploy flows",
    link: "https://chatgpt.com/g/g-67ebb39985c88191bde258e563a05af8-promptbuilder-architect",
    category: "Programming",
    type: "Custom GPT",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "19",
    name: "Unstuck - Newsletter Assistant",
    description: "Creates bold, high-impact newsletters in Aaron Kolosik's voice, using his podcast style.",
    link: "https://chatgpt.com/g/g-67bd5badb390819198e65a35d8affc54-unstuck-newsletter-assistant",
    category: "Productivity",
    setting: "Private Link",
    featured: false,
  },
  {
    id: "20",
    name: "Dropshipping AI Assistant",
    description: "AI-powered tool for automating dropshipping workflows and optimizing product strategy",
    link: "https://chatgpt.com/g/g-67a80e4a464881919f740d5178f2c8dd-dropshipping-ai-assistant",
    category: "Productivity",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "21",
    name: "GPT Project Instructions Builder",
    description: "The ultimate builder for elite, deployment-ready GPT Instructions and PRDs",
    link: "https://chatgpt.com/g/g-67a6bd4478e88191ab5fe72a7a0c7375-gpt-project-instructions-builder",
    category: "Programming",
    type: "Custom GPT",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "22",
    name: "Dynamic GPT Project Generator",
    description: "Generates GPT-based projects using PRD and UI inputs.",
    link: "https://chatgpt.com/g/g-67a6627ce5e08191be699f5c2f58eef0-dynamic-gpt-project-generator",
    category: "Programming",
    type: "Custom GPT",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "23",
    name: "Cloud Course Assistant",
    description: "Your personal cloud study assistant",
    link: "https://chatgpt.com/g/g-67a65a6345648191aef0686947a54223-cloud-course-assistant",
    category: "Education",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "24",
    name: "Project Structure Architect",
    description: "Generates dynamic project structures from PRDs.",
    link: "https://chatgpt.com/g/g-67a5092e227c81919212f7862604d5cf-project-structure-architect",
    category: "Programming",
    type: "Custom GPT",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "25",
    name: "(PRD) Product Requirements Document Builder",
    description: "Generates PRDs, instructions, and custom resources.",
    link: "https://chatgpt.com/g/g-67a465d99950819186563b257bac0d88-prd-product-requirements-document-builder",
    category: "Research & Analysis",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "26",
    name: "Tax Assistant Pro GPT",
    description: "Guide users through personal and business tax preparation.",
    link: "https://chatgpt.com/g/g-67a279ecea1481919e8ddc3179102670-tax-assistant-pro-gpt",
    category: "Productivity",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "27",
    name: "Call Insights Assistant",
    description: "Analyzes client calls, provides summaries and updates sheets.",
    link: "https://chatgpt.com/g/g-67a27017ace48191aed2c1b72bbf8f9d-call-insights-assistant",
    category: "Productivity",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "28",
    name: "Texts Not to Send",
    description: "Send messages to me, not your ex",
    link: "https://chatgpt.com/g/g-67a26b57cb6881918da575f7c7db4129-texts-not-to-send",
    category: "Lifestyle",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "29",
    name: "Dynamic Resource Aggregator",
    description: "Dynamic resource aggregator with user-defined tables.",
    link: "https://chatgpt.com/g/g-67a132ccde2c8191bc1c6f5aaa8a118b-dynamic-resource-aggregator",
    category: "Research & Analysis",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "30",
    name: "Job Link Parser & Tracker",
    description: "Parses job links and creates tracking spreadsheets.",
    link: "https://chatgpt.com/g/g-67a119ca27a8819189c4d16e1c18d3cc-job-link-parser-tracker",
    category: "Productivity",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "31",
    name: "WealthMind AI",
    description: "A personal budget tracker and financial guide.",
    link: "https://chatgpt.com/g/g-67a0f3c833348191b20061efa83d5847-wealthmind-ai",
    category: "Productivity",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "32",
    name: "Job Search Assistant",
    description: "Parse job links, track jobs, and generate tailored resumes",
    link: "https://chatgpt.com/g/g-679fe1e9d5248191849631baced67ec5-job-search-assistant",
    category: "Productivity",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "33",
    name: "RAG-DAL Knowledgebase Builder",
    description:
      "Autonomous Knowledge Base (RAG) Builder for Retrieval-Augmented Generation for Dynamic Autonomous Learning",
    link: "https://chatgpt.com/g/g-679e8aa68d70819185c2f072b4bf2065-rag-dal-knowledgebase-builder",
    category: "Research & Analysis",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "34",
    name: "Tenny Search",
    description: "Save apartment listing links and parse them into organized CSV format.",
    link: "https://chatgpt.com/g/g-679b58aee3488191baf80c3c9ad90bef-tenny-search",
    category: "Productivity",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "35",
    name: "Jesus Guide Me",
    description: "Guides users in Bible and Gnostic study with tailored questions and reflective notes.",
    link: "https://chatgpt.com/g/g-67a0293f54ec8191a8a7925eb7800963-jesus-guide-me",
    category: "Education",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "36",
    name: "ApplyGPT",
    description: "Guides users in crafting job applications and preparing for interviews.",
    link: "https://chatgpt.com/g/g-679afade60e48191aba8bf66a54d8e8a-applygpt",
    category: "Productivity",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "37",
    name: "Assistant Template Generator",
    description: "Generates OpenAI Assistant API templates and setup guides.",
    link: "https://chatgpt.com/g/g-67853e2243348191ab1ad2f89c02d3ef-assistant-template-generator",
    category: "Programming",
    type: "Custom GPT",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "38",
    name: "Personal Video Coach",
    description: "Creates professional video scripts for job pitches or any subject you choose.",
    link: "https://chatgpt.com/g/g-678433cdeaa481918b3e95c5cfccb32d-personal-video-coach",
    category: "Productivity",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "39",
    name: "Cosmic Oracle",
    description: "Your cosmic guide for personalized astrology insights.",
    link: "https://chatgpt.com/g/g-6781683b25b88191be28d4d4596c746e-cosmic-oracle",
    category: "Lifestyle",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "40",
    name: "The Profile Wingman",
    description: "Optimize dating profiles with engaging, app-specific content.",
    link: "https://chatgpt.com/g/g-6781573a72dc81919c5d98ef9d0e67bb-the-profile-wingman",
    category: "Lifestyle",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "41",
    name: "Musk Insights Tracker",
    description: "Tracks Elon Musk's social, financial, and political influence.",
    link: "https://chatgpt.com/g/g-678155531ef08191b64844337cdefc05-musk-insights-tracker",
    category: "Lifestyle",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "42",
    name: "Driving Test Genius",
    description: "US Driving Test Prep Assistant for all states.",
    link: "https://chatgpt.com/g/g-677f99e5db28819194f03aed0ae7bd58-driving-test-genius",
    category: "Education",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "43",
    name: "DOGER",
    description: "Analyzes budgets to find inefficiencies, propose AI solutions, and inspire community contributions.",
    link: "https://chatgpt.com/g/g-677f30c415208191ac4429c9952a492d-doger",
    category: "Research & Analysis",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "44",
    name: "AI Palmistry Guide",
    description: "AI-powered virtual palm reader offering insightful, accurate, and personalized palm readings.",
    link: "https://chatgpt.com/g/g-677d762e938481919973a4b587184c40-ai-palmistry-guide",
    category: "Lifestyle",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "45",
    name: "Artist Budget Guide",
    description: "Helps artists create realistic budgets for their projects.",
    link: "https://chatgpt.com/g/g-677c38ca83cc8191962b0d2e84a8f377-artist-budget-guide",
    category: "Productivity",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "46",
    name: "Unleash Your Sales Greatness",
    description:
      "Empowers users with practical, empathetic sales training and growth strategies. Powered by unleashyoursalesgreatness.com",
    link: "https://chatgpt.com/g/g-6778556e2ef481918fdead30de50fb95-unleash-your-sales-greatness",
    category: "Productivity",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "47",
    name: "SongByrd",
    description: "Your ultimate AI-powered songwriting assistant for hits.",
    link: "https://chatgpt.com/g/g-67723c217e1481918982a34fe2bf360d-songbyrd",
    category: "Productivity",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "48",
    name: "Elite Design Studio",
    description: "Agency-level designer with GPT-4o power for elite branding and visual identity systems",
    link: "https://chatgpt.com/g/g-67721e4ac2008191b639f731f8f2b908-elite-design-studio",
    category: "DALL·E",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "49",
    name: "DCASE 312",
    description:
      "Your AI-powered cultural engagement guide for Chicago's Department of Cultural Affairs and Special Events (DCASE).",
    link: "https://chatgpt.com/g/g-676ad343f78c81919598a8969432a163-dcase-312",
    category: "Productivity",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "50",
    name: "A&R Campaign Architect",
    description: "Elite A&R strategist for artist campaigns across blogs, playlists, venues, and licensing platforms",
    link: "https://chatgpt.com/g/g-676aa9f4295081918c546999524f2e84-a-r-campaign-architect",
    category: "Productivity",
    setting: "GPT Store",
    featured: true,
  },
  // Adding more GPTs from the list
  {
    id: "51",
    name: "Instruction Architect",
    description: "Setting the gold standard for AI system instruction design.",
    link: "https://chatgpt.com/g/g-676964c88b088191b70dcd4133ae2595-1-system-instruction-architect",
    category: "Productivity",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "52",
    name: "Artispreneur Email Generator",
    description: "Generate emails for your music campaign",
    link: "https://chatgpt.com/g/g-676913cfd1d48191b595497379d27d99-artispreneur-email-generator",
    category: "Writing",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "53",
    name: "PlaceCode",
    description:
      "Designs and optimizes web solutions with tailored scripts, seamless integrations, and deployment-ready assets.",
    link: "https://chatgpt.com/g/g-67689e24ba088191915d9f046ca55c6d-placecode",
    category: "Programming",
    type: "Custom GPT",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "54",
    name: "Horizon UI Copilot",
    description: "Build and deploy sleek UIs for assistants using Horizon UI.",
    link: "https://chatgpt.com/g/g-6765c87b5548819197f8a8b5191d253c-horizon-ui-copilot",
    category: "Programming",
    type: "Custom GPT",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "55",
    name: "Custom UI Chatbot Assistant",
    description: "Configures CSS/HTML Templates and project files to match open ai assistant apis",
    link: "https://chatgpt.com/g/g-67612822fb34819198549b0396a5d6e5-custom-ui-chatbot-assistant",
    category: "Programming",
    type: "Custom GPT",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "56",
    name: "Omni Architect",
    description: "Master problem solver and workflow designer across all domains.",
    link: "https://chatgpt.com/g/g-6749234181b88191a9e9cf4940f29900-omni-architect",
    category: "Productivity",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "57",
    name: "Sixth Automation",
    description: "Expert automation assistant for Make.com and Softr scenarios.",
    link: "https://chatgpt.com/g/g-673eed917eec81918514e2a40f890fd6-sixth-automation",
    category: "Productivity",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "58",
    name: "Artist Business Plan Generator",
    description: "Guides artists in building tailored business plans and growth strategies.",
    link: "https://chatgpt.com/g/g-673240bec7c08190af4bf954dcef16a5-artist-business-plan-generator",
    category: "Business",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "59",
    name: "HouseofAshburn Executive Assistant",
    description: "Luxury brand executive assistant driving strategic growth",
    link: "https://chatgpt.com/g/g-WtZYSpBvN-houseofashburn-executive-assistant",
    category: "Business",
    setting: "Private Link",
    featured: false,
  },
  {
    id: "60",
    name: "My Smart Tax Advisor",
    description: "Personalized U.S. tax assistant for entrepreneurs",
    link: "https://chatgpt.com/g/g-MQEBlp8iN-my-smart-tax-advisor",
    category: "Finance",
    setting: "GPT Store",
    featured: false,
  },
  // Adding more entries to reach at least 100 GPTs
  {
    id: "61",
    name: "Image Sourcing Analyst",
    description: "Extracts relevant image URLs from sites for visual content enhancement",
    link: "https://chatgpt.com/g/g-bVKch7kAf-image-sourcing-analyst",
    category: "Research & Analysis",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "62",
    name: "RSS Assist",
    description: "Transforms RSS feeds into engaging, SEO-optimized blogs with ethical attribution and rich insights.",
    link: "https://chatgpt.com/g/g-gOBjQdiWm-rss-assist",
    category: "Writing",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "63",
    name: "NPAO Bot",
    description: "Helps users prioritize and analyze tasks using N.P.A.O. for clarity and growth.",
    link: "https://chatgpt.com/g/g-5BWmDw3PN-npao-bot",
    category: "Productivity",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "64",
    name: "The Tie Breaker",
    description: "Builds a futuristic voting platform driven by AI and blockchain for smart governance.",
    link: "https://chatgpt.com/g/g-N1teuetQp-the-tie-breaker",
    category: "Programming",
    type: "Custom GPT",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "65",
    name: "Ultimate Survival AI",
    description: "Your definitive companion for mastering survival in any environment.",
    link: "https://chatgpt.com/g/g-NujG6TmqR-ultimate-survival-ai",
    category: "Lifestyle",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "66",
    name: "Visual Content Studio",
    description: "Convert text into visual formats, automate creative workflows, and generate product videos.",
    link: "https://chatgpt.com/g/g-VEJl08aRo-visual-content-studio",
    category: "DALL-E",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "67",
    name: "Sales Process Assistant",
    description: "AI assistant for seamless sales automation, CRM integration, and actionable sales insights.",
    link: "https://chatgpt.com/g/g-HqlEVB4Se-sales-process-assistant",
    category: "Business",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "68",
    name: "Business Automation Guide",
    description: "Expert guide for automating business workflows and integrating tools like Softr, Zapier, and GPT.",
    link: "https://chatgpt.com/g/g-f4GHCIImp-business-automation-guide",
    category: "Business",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "69",
    name: "Technical Writing Pro",
    description: "Expert in refining technical copy, creating processes, and crafting goal-oriented documents.",
    link: "https://chatgpt.com/g/g-DfNpo3dNS-technical-writing-pro",
    category: "Writing",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "70",
    name: "Crime Tracker Chicago",
    description: "Real-time crime intelligence for Chicago with maps, reports, and predictive analytics.",
    link: "https://chatgpt.com/g/g-pKjwPnJ18-crime-tracker-chicago",
    category: "Research & Analysis",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "71",
    name: "Outreach Automator",
    description: "Automates email outreach tasks in HubSpot with personalized emails.",
    link: "https://chatgpt.com/g/g-lISjbhdPs-outreach-automator",
    category: "Business",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "72",
    name: "Strategic Business Architect",
    description: "Expert guide for strategic growth, sales optimization, and business model innovation.",
    link: "https://chatgpt.com/g/g-sVjPH8xUg-strategic-business-architect",
    category: "Business",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "73",
    name: "AutomateGPT",
    description: "Automate custom GPT creation based on Airtable data.",
    link: "https://chatgpt.com/g/g-p7fv7jXmo-automategpt",
    category: "Programming",
    type: "Custom GPT",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "74",
    name: "Unstuck Master Plan GPT",
    description: "Conversational AI coach guiding users step-by-step through the Power Assessment.",
    link: "https://chatgpt.com/g/g-73w9nmSXx-unstuck-master-plan-gpt",
    category: "Productivity",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "75",
    name: "Business Audit",
    description: "Dynamic business audit and strategic planning assistant.",
    link: "https://chatgpt.com/g/g-ATFdQizuP-business-audit",
    category: "Business",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "76",
    name: "GPT Configurator",
    description: "Creates detailed, formatted documents from GPT configurations.",
    link: "https://chatgpt.com/g/g-rIfzVdt47-gpt-configurator",
    category: "Programming",
    type: "Custom GPT",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "77",
    name: "BLK Heights Career Coach",
    description:
      "Empowering coach and content guide for BLK Heights' tech-driven community. Powered by www.blkheights.com.",
    link: "https://chatgpt.com/g/g-faUugyEGJ-blk-heights-career-coach",
    category: "Education",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "78",
    name: "List Manager",
    description: "Organizes and manages apartment listings with categorization and search tools.",
    link: "https://chatgpt.com/g/g-ZJWsFRQRZ-list-manager",
    category: "Productivity",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "79",
    name: "HUMINT",
    description: "Simulates and teaches human intelligence skills focused on self-awareness and empathy.",
    link: "https://chatgpt.com/g/g-vZ4ywRsqf-humint",
    category: "Education",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "80",
    name: "Image Scraper Pro",
    description: "Efficient GPT for scraping and returning relevant image URLs.",
    link: "https://chatgpt.com/g/g-FuPsdlwkZ-image-scraper-pro",
    category: "Research & Analysis",
    setting: "GPT Store",
    featured: false,
  },
  // Adding more entries to complete the list
  {
    id: "81",
    name: "Web Image Extractor",
    description: "Extracts and returns the most relevant image URLs from websites.",
    link: "https://chatgpt.com/g/g-SrwBDwnJd-web-image-extractor",
    category: "Research & Analysis",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "82",
    name: "Political Campaign Guide",
    description:
      "Your comprehensive guide for political campaigns and elections, providing direct answers and insights.",
    link: "https://chatgpt.com/g/g-tL61iT0zl-political-campaign-guide",
    category: "Research & Analysis",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "83",
    name: "Prossley",
    description:
      "AI-powered sales architect delivering actionable, data-driven insights for optimized client engagement.",
    link: "https://chatgpt.com/g/g-s0HyR5nM8-prossley",
    category: "Business",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "84",
    name: "Revenue Strategist",
    description: "Guides businesses in crafting custom sales strategies using Predictable Revenue Modeling.",
    link: "https://chatgpt.com/g/g-IkaglNabJ-revenue-strategist",
    category: "Business",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "85",
    name: "ArtBeat Covers",
    description: "Helps artists create visually stunning cover art tailored to their music.",
    link: "https://chatgpt.com/g/g-Ja6aQCuTg-artbeat-covers",
    category: "DALL-E",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "86",
    name: "Music Biz Daily Digest",
    description: "Creates a daily digest of top music industry business news.",
    link: "https://chatgpt.com/g/g-tkvx0g5zl-music-biz-daily-digest",
    category: "Writing",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "87",
    name: "Artist Resource Hub",
    description: "Your ultimate guide to music industry resources, deals, and news.",
    link: "https://chatgpt.com/g/g-gmfOMW8bv-artist-resource-hub",
    category: "Research & Analysis",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "88",
    name: "Hero Image Extractor Pro",
    description: "Effortlessly extracts hero images from websites for seamless data integration.",
    link: "https://chatgpt.com/g/g-kyazQOR1h-hero-image-extractor-pro",
    category: "Research & Analysis",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "89",
    name: "Mighty Oaks Capital Assistant",
    description: "AI chatbot for MightyOaksCapitalPartners.com, streamlining user inquiries and engagement.",
    link: "https://chatgpt.com/g/g-pB6vFykTE-mighty-oaks-capital-assistant",
    category: "Business",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "90",
    name: "GPT Creator Pro",
    description: "Advanced GPT architect specializing in prompt engineering, optimization, and deployment.",
    link: "https://chatgpt.com/g/g-s9YtL560v-gpt-creator-pro",
    category: "Programming",
    type: "Custom GPT",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "91",
    name: "DocuScript",
    description: "Guide users in creating compelling documentaries from start to finish.",
    link: "https://chatgpt.com/g/g-fohlSe9g9-docuscript",
    category: "Writing",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "92",
    name: "AI Newsletter Assistant",
    description: "Builds and writes daily AI newsletters with fresh news and smart resource curation.",
    link: "https://chatgpt.com/g/g-68120a8c7aa08191bd2da528ea3bd7ee-ai-newsletter-assistant",
    category: "Writing",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "93",
    name: "Artist Interview Bot",
    description: "Collects and shares artists' insights for aspiring talents.",
    link: "https://chatgpt.com/g/g-mMIuI7n2u-artist-interview-bot",
    category: "Writing",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "94",
    name: "EPK Builder",
    description: "Creates EPKs for musicians, crafting engaging bios and media kits.",
    link: "https://chatgpt.com/g/g-k1G0USEyh-epk-builder",
    category: "Writing",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "95",
    name: "Artist AI Coach",
    description: "Connects artists with AI-powered personal tutors based on real artist experiences.",
    link: "https://chatgpt.com/g/g-y8hqJDMiF-artist-ai-coach",
    category: "Lifestyle",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "96",
    name: "ArtistConnect",
    description: "Connect with artists for real advice, mentorship, and coaching based on true journeys.",
    link: "https://chatgpt.com/g/g-EWhVQersh-artistconnect",
    category: "Education",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "97",
    name: "ChicagoESQ",
    description: "Learn about Chicago Justice System",
    link: "https://chatgpt.com/g/g-N0Vkz5UV0-chicagoesq",
    category: "Education",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "98",
    name: "ERC Assistant",
    description: "Guides in filling out employee retention credit forms",
    link: "https://chatgpt.com/g/g-bq6pdBN1d-erc-assistant",
    category: "Finance",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "99",
    name: "AlgoVest",
    description: "Personal Investment Algorithm Creator",
    link: "https://chatgpt.com/g/g-ZKskCRKA7-algovest",
    category: "Finance",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "100",
    name: "RSS Aggregator",
    description: "Curates and exports tailored RSS feed lists for any industry or niche.",
    link: "https://chatgpt.com/g/g-jKy7Famu9-rss-aggregator",
    category: "Research & Analysis",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "101",
    name: "Side Hustle Finder",
    description: "Helps users discover quick and easy side hustle opportunities via mobile apps and platforms.",
    link: "https://chatgpt.com/g/g-PVbv64iXx-side-hustle-finder",
    category: "Business",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "102",
    name: "FlowBud",
    description: "Build custom agents with OpenAI, Zapier, Make, Dialogflow, and more.",
    link: "https://chatgpt.com/g/g-BlpSmLwM3-flowbud",
    category: "Programming",
    type: "Custom GPT",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "103",
    name: "Highly Suggested Prompts (HSPs)",
    description: "Refines prompts with precision for optimal AI performance and clarity.",
    link: "https://chatgpt.com/g/g-haeo2jTUS-highly-suggested-prompts-hsps",
    category: "Programming",
    type: "Custom GPT",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "104",
    name: "Relevance AI Custom Agent Builder",
    description:
      "Uses Relevance.ai documentation to help guide you with agent, tool and bot creation. Just enter a prompt of what you'd like to build!",
    link: "https://chatgpt.com/g/g-pSPhvxvMh-relevance-ai-custom-agent-builder",
    category: "Programming",
    type: "Custom GPT",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "105",
    name: "Relevance AI Assistant",
    description:
      "Uses Relevance.ai documentation to help guide you with agent, tool and bot creation. Just enter a prompt of what you'd like to build!",
    link: "https://chatgpt.com/g/g-bymrCVdYD-relevance-ai-assistant",
    category: "Programming",
    type: "Custom GPT",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "106",
    name: "Jo Kraft",
    description: "Expert joke crafter who helps develop jokes based on user's style.",
    link: "https://chatgpt.com/g/g-pCiEuWm6P-jo-kraft",
    category: "Writing",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "107",
    name: "Showcase",
    description: "Create your open mic, showcase, or release party.",
    link: "https://chatgpt.com/g/g-Fzqo1n15t-showcase",
    category: "Lifestyle",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "108",
    name: "Artist Bio Creator",
    description: "Guides musicians through creating professional artist biographies.",
    link: "https://chatgpt.com/g/g-aWdPi7rXs-artist-bio-creator",
    category: "Writing",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "109",
    name: "Stori",
    description:
      "I'll guide you through writing professional scripts and storyboards, complete with visual storytelling tools.",
    link: "https://chatgpt.com/g/g-e1Hu90qGa-stori",
    category: "Writing",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "110",
    name: "Uney: Illinois Unemployment Guide",
    description: "Expert on Illinois unemployment insurance.",
    link: "https://chatgpt.com/g/g-cUZm3JhdJ-uney-illinois-unemployment-guide",
    category: "Finance",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "111",
    name: "Recalla",
    description: "Intuitive recall agent providing detailed recall lists.",
    link: "https://chatgpt.com/g/g-Y4fMRqFFf-recalla",
    category: "Research & Analysis",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "112",
    name: "Code Camp Mentor",
    description: "Your personalized coding bootcamp tutor for Python and AI.",
    link: "https://chatgpt.com/g/g-b1hlsjRXX-code-camp-mentor",
    category: "Programming",
    type: "Custom GPT",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "113",
    name: "Sales Commander",
    description: "General of Your Sales Army",
    link: "https://chatgpt.com/g/g-MqLy87WdT-sales-commander",
    category: "Business",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "114",
    name: "Armie",
    description: "Advanced artist development and management bot assisting artists to become entrepreneurs.",
    link: "https://chatgpt.com/g/g-YwyaCFT7Y-armie",
    category: "Business",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "115",
    name: "AuctoPilot",
    description: "Find auctions, foreclosures, estate sales near you.",
    link: "https://chatgpt.com/g/g-98xUvWZ0A-auctopilot",
    category: "Lifestyle",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "116",
    name: "Theory Formulation Assistant",
    description:
      "Assists in theory formulation and investigation, explaining and applying the 'nx' theory, where x represents known possibilities and n represents unknown possibilities.",
    link: "https://chatgpt.com/g/g-sxSTVv4og-theory-formulation-assistant",
    category: "Research & Analysis",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "117",
    name: "InterviewGPT",
    description: "Streamlined job application assistant for optimizing resumes and managing application tracking.",
    link: "https://chatgpt.com/g/g-IcSrCDQKp-interviewgpt",
    category: "Productivity",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "118",
    name: "Algorithm Architect",
    description: "Helps create algorithms and code with tutorials.",
    link: "https://chatgpt.com/g/g-U2en92Qdn-algorithm-architect",
    category: "Programming",
    type: "Custom GPT",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "119",
    name: "WordUp",
    description: "Wordpress Assistant",
    link: "https://chatgpt.com/g/g-L6f108GSb-wordup",
    category: "Programming",
    type: "Custom GPT",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "120",
    name: "API Guide",
    description:
      "Allow me to make custom actions and functions using APIs, by uploading documentation and asking for step-by-step instructions.",
    link: "https://chatgpt.com/g/g-vSbY2y8pd-api-guide",
    category: "Programming",
    type: "Custom GPT",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "121",
    name: "SyncMaster",
    description: "Find music supervisors and libraries to submit your music to.",
    link: "https://chatgpt.com/g/g-hvolaQ0yh-syncmaster",
    category: "Music",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "122",
    name: "SongVid",
    description: "Powered by Artispreneur. Create a music video with stock footage based on a song upload",
    link: "https://chatgpt.com/g/g-z0ounFAlV-songvid",
    category: "DALL-E",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "123",
    name: "Reggie: P.R.O.",
    description: "A specialized assistant helping users register for PROs and manage music portfolios.",
    link: "https://chatgpt.com/g/g-2eyNECKRg-reggie-p-r-o",
    category: "Music",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "124",
    name: "MicSpot",
    description:
      "Powered by Artispreneur. This GPT finds open mics in your area for Comedy and Music. All content generated from www.badslava.com",
    link: "https://chatgpt.com/g/g-maDxBXHrX-micspot",
    category: "Lifestyle",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "125",
    name: "E-Milly",
    description: "Crafts data-driven campaigns for music promotion.",
    link: "https://chatgpt.com/g/g-gmDJhtOzO-e-milly",
    category: "Marketing",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "126",
    name: "Product Description Editor",
    description: "Creates polished product descriptions for ecommerce platforms like WooCommerce.",
    link: "https://chatgpt.com/g/g-kHM2PFMAp-product-description-editor",
    category: "Writing",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "127",
    name: "MusicTracts - Split Sheet Agreement",
    description: "Your go-to tool for generating professional Music Split Sheet Agreements effortlessly.",
    link: "https://chatgpt.com/g/g-xtRcRaLBy-musictracts-split-sheet-agreement",
    category: "Legal",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "128",
    name: "Music Contract Assistant",
    description:
      "Powered by Artispreneur.com. Enter a prompt for a music contract, upload your own for review, or submit your information to fill in a template.",
    link: "https://chatgpt.com/g/g-8a5gA1RQf-music-contract-assistant",
    category: "Legal",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "129",
    name: "Textvi",
    description: "Upload text and create video",
    link: "https://chatgpt.com/g/g-FULmAXEmh-textvi",
    category: "DALL-E",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "130",
    name: "API Integration Architect Pro",
    description: "Expert in API schema creation, validation, and seamless AI integrations.",
    link: "https://chatgpt.com/g/g-9KZmYIrNN-api-integration-architect-pro",
    category: "Programming",
    type: "Custom GPT",
    setting: "GPT Store",
    featured: false,
  },
  // --- AI TOOLS & AGENTS (NEW) ---
  {
    id: "201",
    name: "OpenAI (ChatGPT)",
    description: "Multimodal AI for text, image, audio, and video generation and reasoning.",
    link: "https://openai.com",
    category: "Assistants & Chatbots",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "202",
    name: "Anthropic Claude",
    description: "AI assistant optimized for thoughtful writing, complex reasoning, and coding.",
    link: "https://claude.ai",
    category: "Assistants & Chatbots",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "203",
    name: "Google Gemini",
    description: "Advanced AI multimodal model integrated with Google Workspace and search.",
    link: "https://gemini.google.com",
    category: "Assistants & Chatbots",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "204",
    name: "Perplexity AI",
    description: "Conversational search engine providing cited, real-time answers to queries.",
    link: "https://perplexity.ai",
    category: "Search & Research",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "205",
    name: "Claude Code",
    description: "Anthropic's CLI tool for agentic coding and terminal-based AI assistance.",
    link: "https://anthropic.com",
    category: "Programming",
    type: "AI Agent",
    featured: true,
  },
  {
    id: "206",
    name: "Clawdbot",
    description: "Powerful agentic workspace for running AI agents and complex workflows.",
    link: "https://clawdbot.ai",
    category: "Programming",
    type: "AI Agent",
    featured: true,
  },
  {
    id: "207",
    name: "Gamma.app",
    description: "Generates beautiful presentations, websites, and documents from a single prompt.",
    link: "https://gamma.app",
    category: "Design & Presentations",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "208",
    name: "Cursor",
    description: "The AI-first code editor built for pair programming with Large Language Models.",
    link: "https://cursor.com",
    category: "Programming",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "209",
    name: "v0.dev",
    description: "Generative UI system by Vercel that builds React components from text prompts.",
    link: "https://v0.dev",
    category: "Programming",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "210",
    name: "n8n",
    description: "Workflow automation tool for technical teams to build complex AI agents and logic.",
    link: "https://n8n.io",
    category: "Productivity",
    type: "Automation",
    featured: true,
  },
  {
    id: "211",
    name: "Midjourney",
    description: "High-quality AI image generator known for artistic and hyper-realistic visuals.",
    link: "https://midjourney.com",
    category: "DALL-E",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "212",
    name: "ElevenLabs",
    description: "Industry-leading AI voice generator and text-to-speech platform.",
    link: "https://elevenlabs.io",
    category: "Music",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "213",
    name: "Runway Gen-3",
    description: "Next-generation video generation model for cinematic AI-generated video.",
    link: "https://runwayml.com",
    category: "Video",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "214",
    name: "Synthesia",
    description: "Create AI videos with talking avatars for training and marketing content.",
    link: "https://synthesia.io",
    category: "Video",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "215",
    name: "HeyGen",
    description: "AI video generation platform for creating professional videos with AI avatars.",
    link: "https://heygen.com",
    category: "Video",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "216",
    name: "Jasper AI",
    description: "Enterprise AI content platform for marketing, copywriting, and blog generation.",
    link: "https://jasper.ai",
    category: "Writing",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "217",
    name: "Copy.ai",
    description: "AI platform for sales and marketing teams to automate high-scale content tasks.",
    link: "https://copy.ai",
    category: "Writing",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "218",
    name: "Notion AI",
    description: "Integrated AI features for brainstorming, summarizing, and writing inside Notion.",
    link: "https://notion.so",
    category: "Productivity",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "219",
    name: "Zapier Central",
    description: "Build custom AI agents that can take actions across 6,000+ apps.",
    link: "https://zapier.com/central",
    category: "Productivity",
    type: "Automation",
    featured: true,
  },
  {
    id: "220",
    name: "Make.com",
    description: "Visual automation platform to connect apps and build AI-driven workflows.",
    link: "https://make.com",
    category: "Productivity",
    type: "Automation",
    featured: false,
  },
  {
    id: "221",
    name: "Suno",
    description: "Generate full songs with vocals, lyrics, and instrumentation from text.",
    link: "https://suno.com",
    category: "Music",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "222",
    name: "Udio",
    description: "High-fidelity music generation platform for professional-sounding AI tracks.",
    link: "https://udio.com",
    category: "Music",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "223",
    name: "Pika Labs",
    description: "Imaginative AI video generator capable of animating images and creating clips.",
    link: "https://pika.art",
    category: "Video",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "224",
    name: "Luma Dream Machine",
    description: "High-quality video generator that creates realistic video from text and images.",
    link: "https://lumalabs.ai",
    category: "Video",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "225",
    name: "Leonardo.ai",
    description: "Creative production platform for generating high-quality art and textures.",
    link: "https://leonardo.ai",
    category: "DALL-E",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "226",
    name: "Grammarly AI",
    description: "AI-powered writing assistant for grammar, tone, and full sentence rewrites.",
    link: "https://grammarly.com",
    category: "Writing",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "227",
    name: "Descript",
    description: "AI video and audio editor that works like a text document.",
    link: "https://descript.com",
    category: "Video",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "228",
    name: "Otter.ai",
    description: "AI meeting assistant that records, transcribes, and summarizes conversations.",
    link: "https://otter.ai",
    category: "Productivity",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "229",
    name: "Fireflies.ai",
    description: "Transcription and meeting analysis tool for automating notes across platforms.",
    link: "https://fireflies.ai",
    category: "Productivity",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "230",
    name: "Reclaim.ai",
    description: "AI scheduling for your calendar that automatically finds time for tasks and habits.",
    link: "https://reclaim.ai",
    category: "Productivity",
    type: "Automation",
    featured: true,
  },
  {
    id: "231",
    name: "Clay",
    description: "AI-powered sales prospecting tool that enriches leads and automates outreach.",
    link: "https://clay.com",
    category: "Business",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "232",
    name: "Apollo.io",
    description: "Sales intelligence platform with AI-driven lead scoring and automated workflows.",
    link: "https://apollo.io",
    category: "Business",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "233",
    name: "Beautiful.ai",
    description: "AI presentation software that automatically handles layout and design.",
    link: "https://beautiful.ai",
    category: "Design & Presentations",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "234",
    name: "Tome",
    description: "AI-powered storytelling platform for generating pitch decks and narratives.",
    link: "https://tome.app",
    category: "Design & Presentations",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "235",
    name: "Ideogram",
    description: "AI image generator specializing in high-quality typography and graphic design.",
    link: "https://ideogram.ai",
    category: "DALL-E",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "236",
    name: "Sora (OpenAI)",
    description: "Upcoming high-fidelity text-to-video model capable of photorealistic scenes.",
    link: "https://openai.com/sora",
    category: "Video",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "237",
    name: "GitHub Copilot",
    description: "AI pair programmer that provides code suggestions and context-aware fixes.",
    link: "https://github.com/features/copilot",
    category: "Programming",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "238",
    name: "Replit Agent",
    description: "AI assistant that helps you build full applications from scratch within Replit.",
    link: "https://replit.com",
    category: "Programming",
    type: "AI Agent",
    featured: true,
  },
  {
    id: "239",
    name: "Lovable",
    description: "Vibe-coding platform that builds and deploys web applications from natural language.",
    link: "https://lovable.dev",
    category: "Programming",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "240",
    name: "Bolt.new",
    description: "Full-stack web application generator that runs entirely in the browser using AI.",
    link: "https://bolt.new",
    category: "Programming",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "241",
    name: "Tabnine",
    description: "AI code completion tool supporting a large variety of IDEs and languages.",
    link: "https://tabnine.com",
    category: "Programming",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "242",
    name: "Anthropic Console",
    description: "Developer platform for testing Claude prompts and generating Python code snippets.",
    link: "https://console.anthropic.com",
    category: "Programming",
    type: "Developer Tool",
    featured: false,
  },
  {
    id: "243",
    name: "Mistral AI",
    description: "High-performance open-source models for a wide range of text reasoning tasks.",
    link: "https://mistral.ai",
    category: "Assistants & Chatbots",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "244",
    name: "Groq",
    description: "Ultra-fast LPU inference engine for running LLMs at lightning speeds.",
    link: "https://groq.com",
    category: "Programming",
    type: "Developer Tool",
    featured: true,
  },
  {
    id: "245",
    name: "Writesonic",
    description: "AI content generator with integrated SEO tools and AI-driven chatbots.",
    link: "https://writesonic.com",
    category: "Writing",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "246",
    name: "Surfer SEO",
    description: "AI-driven SEO tool that helps optimize content for search engine rankings.",
    link: "https://surferseo.com",
    category: "Marketing",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "247",
    name: "QuillBot",
    description: "AI-powered paraphrasing and summarizing tool for writers and students.",
    link: "https://quillbot.com",
    category: "Writing",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "248",
    name: "Hemingway Editor Plus",
    description: "AI version of the classic editor that simplifies and improves your writing style.",
    link: "https://hemingwayapp.com",
    category: "Writing",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "249",
    name: "Canva Magic Studio",
    description: "Comprehensive AI design suite for photo editing, text-to-image, and layout.",
    link: "https://canva.com",
    category: "DALL-E",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "250",
    name: "Adobe Firefly",
    description: "Generative AI models optimized for creative professionals and commercial use.",
    link: "https://firefly.adobe.com",
    category: "DALL-E",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "251",
    name: "Kling AI",
    description: "Highly realistic text-to-video generator capable of long-duration cinematic clips.",
    link: "https://klingai.com",
    category: "Video",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "252",
    name: "Luma AI Genie",
    description: "AI text-to-3D generator that creates production-ready 3D assets.",
    link: "https://lumalabs.ai/genie",
    category: "DALL-E",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "253",
    name: "Scribe",
    description: "Automatically generates step-by-step guides by recording your browser actions.",
    link: "https://scribehow.com",
    category: "Productivity",
    type: "Automation",
    featured: false,
  },
  {
    id: "254",
    name: "Taskade Agents",
    description: "Build an autonomous AI workforce for project management and brainstorming.",
    link: "https://taskade.com",
    category: "Productivity",
    type: "AI Agent",
    featured: true,
  },
  {
    id: "255",
    name: "CrewAI",
    description: "Framework for orchestrating role-based, autonomous AI agents for complex tasks.",
    link: "https://crewai.com",
    category: "Programming",
    type: "Framework",
    featured: true,
  },
  {
    id: "256",
    name: "AutoGPT",
    description: "Open-source experiment to make GPT-4 fully autonomous for goal-driven tasks.",
    link: "https://github.com/Significant-Gravitas/Auto-GPT",
    category: "Programming",
    type: "Framework",
    featured: false,
  },
  {
    id: "257",
    name: "LangChain",
    description: "Framework for developing applications powered by large language models.",
    link: "https://langchain.com",
    category: "Programming",
    type: "Framework",
    featured: true,
  },
  {
    id: "258",
    name: "FlowiseAI",
    description: "Low-code drag & drop UI to build customized LLM flow using LangChain.",
    link: "https://flowiseai.com",
    category: "Programming",
    type: "No-code Tool",
    featured: true,
  },
  {
    id: "259",
    name: "Botpress",
    description: "Next-gen conversational AI platform to build ChatGPT-like bots for your data.",
    link: "https://botpress.com",
    category: "Business",
    type: "No-code Tool",
    featured: false,
  },
  {
    id: "260",
    name: "Voiceflow",
    description: "Collaborative design platform for building AI-driven voice and chat agents.",
    link: "https://voiceflow.com",
    category: "Business",
    type: "No-code Tool",
    featured: true,
  },
  {
    id: "261",
    name: "Play.ht",
    description: "AI text-to-speech generator for creating professional voiceovers and audio content.",
    link: "https://play.ht",
    category: "Music",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "262",
    name: "Murf.ai",
    description: "AI voice platform that enables users to create life-like voiceovers in minutes.",
    link: "https://murf.ai",
    category: "Music",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "263",
    name: "Suno AI",
    description: "High-quality AI song generator that creates vocals, instruments, and full arrangements.",
    link: "https://suno.com",
    category: "Music",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "264",
    name: "Udio AI",
    description: "Next-generation music generation tool for producing complete studio-quality songs.",
    link: "https://udio.com",
    category: "Music",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "265",
    name: "Julius AI",
    description: "AI data analyst that analyzes spreadsheets, visualizes data, and creates reports.",
    link: "https://julius.ai",
    category: "Research & Analysis",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "266",
    name: "Consensus",
    description: "AI search engine that finds evidence-based answers from scientific research papers.",
    link: "https://consensus.app",
    category: "Research & Analysis",
    type: "Search Tool",
    featured: true,
  },
  {
    id: "267",
    name: "Elicit",
    description: "AI research assistant that automates literature reviews and data extraction.",
    link: "https://elicit.org",
    category: "Research & Analysis",
    type: "Research Tool",
    featured: false,
  },
  {
    id: "268",
    name: "ResearchGate AI",
    description: "AI-enhanced search for exploring millions of scientific publications.",
    link: "https://researchgate.net",
    category: "Research & Analysis",
    type: "Research Tool",
    featured: false,
  },
  {
    id: "269",
    name: "Scite.ai",
    description: "AI tool to see how scientific research has been cited and if it's supported.",
    link: "https://scite.ai",
    category: "Research & Analysis",
    type: "Research Tool",
    featured: false,
  },
  {
    id: "270",
    name: "NotebookLM",
    description: "AI-powered notebook by Google that uses your own documents to ground responses.",
    link: "https://notebooklm.google",
    category: "Research & Analysis",
    type: "Research Tool",
    featured: true,
  },
  {
    id: "271",
    name: "ChatPDF",
    description: "AI tool that allows you to chat with any PDF document to extract insights.",
    link: "https://chatpdf.com",
    category: "Research & Analysis",
    type: "Utility",
    featured: false,
  },
  {
    id: "272",
    name: "Humata",
    description: "AI-powered document analysis for summarizing and chatting with long files.",
    link: "https://humata.ai",
    category: "Research & Analysis",
    type: "Utility",
    featured: false,
  },
  {
    id: "273",
    name: "SheetAI",
    description: "Integrate powerful AI brains directly into your Google Sheets and Excel.",
    link: "https://sheetai.app",
    category: "Finance",
    type: "Plugin",
    featured: false,
  },
  {
    id: "274",
    name: "Formula Bot",
    description: "AI assistant that converts text instructions into complex Excel and Google Sheets formulas.",
    link: "https://formulabot.com",
    category: "Finance",
    type: "Utility",
    featured: false,
  },
  {
    id: "275",
    name: "Rows.com",
    description: "Modern spreadsheet with a built-in AI analyst and powerful integrations.",
    link: "https://rows.com",
    category: "Finance",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "276",
    name: "Gumloop",
    description: "No-code platform for building complex AI-driven data automation workflows.",
    link: "https://gumloop.com",
    category: "Productivity",
    type: "Automation",
    featured: true,
  },
  {
    id: "277",
    name: "Bardeen.ai",
    description: "AI-powered browser automation that extracts data and runs workflows from your tabs.",
    link: "https://bardeen.ai",
    category: "Productivity",
    type: "Automation",
    featured: false,
  },
  {
    id: "278",
    name: "InVideo AI",
    description: "Turn any idea or script into a complete video with voiceover and stock footage.",
    link: "https://invideo.io",
    category: "Video",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "279",
    name: "CapCut Online AI",
    description: "Popular video editor with powerful built-in AI for captions, upscaling, and effects.",
    link: "https://capcut.com",
    category: "Video",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "280",
    name: "OpusClip",
    description: "AI tool that transforms long-form videos into viral short-form clips (TikToks, Reels).",
    link: "https://opus.pro",
    category: "Video",
    type: "Automation",
    featured: true,
  },
  {
    id: "281",
    name: "Motion AI",
    description: "Intelligent calendar and task manager that prioritizes your day using AI.",
    link: "https://usemotion.com",
    category: "Productivity",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "282",
    name: "ClickUp Brain",
    description: "Integrated AI for automated summaries, updates, and project management in ClickUp.",
    link: "https://clickup.com",
    category: "Productivity",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "283",
    name: "Taskade AI",
    description: "AI-powered workspace for productivity with unified chat, notes, and task lists.",
    link: "https://taskade.com",
    category: "Productivity",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "284",
    name: "Mem.ai",
    description: "AI-powered workspace that organizes your notes and thoughts automatically.",
    link: "https://mem.ai",
    category: "Productivity",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "285",
    name: "Fellow.app AI",
    description: "AI meeting agendas, summaries, and action items integration for high-performing teams.",
    link: "https://fellow.app",
    category: "Productivity",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "286",
    name: "Looppanel",
    description: "AI platform for analyzing user research calls and extracting key insights.",
    link: "https://looppanel.com",
    category: "Business",
    type: "Research Tool",
    featured: false,
  },
  {
    id: "287",
    name: "Looka",
    description: "AI-powered platform to design logos and build professional brands in minutes.",
    link: "https://looka.com",
    category: "DALL-E",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "288",
    name: "Logomaker AI",
    description: "Generate professional logo concepts instantly using generative design.",
    link: "https://logomaker.ai",
    category: "DALL-E",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "289",
    name: "Anyword",
    description: "AI writing tool that uses data to predict how well your marketing copy will perform.",
    link: "https://anyword.com",
    category: "Writing",
    type: "Marketing Tool",
    featured: false,
  },
  {
    id: "290",
    name: "AdCreative.ai",
    description: "Generate conversion-focused ad creatives and social media posts using AI.",
    link: "https://adcreative.ai",
    category: "Marketing",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "291",
    name: "FeedHive AI",
    description: "AI-powered social media management for scheduling, engagement, and recycling.",
    link: "https://feedhive.com",
    category: "Marketing",
    type: "Automation",
    featured: true,
  },
  {
    id: "292",
    name: "Buffer AI Assistant",
    description: "AI writing support for creating and scheduling social media posts across platforms.",
    link: "https://buffer.com",
    category: "Marketing",
    type: "Integration",
    featured: false,
  },
  {
    id: "293",
    name: "Hugging Face",
    description: "The 'GitHub of AI' for hosting models, datasets, and demos (Spaces).",
    link: "https://huggingface.co",
    category: "Programming",
    type: "Platform",
    featured: true,
  },
  {
    id: "294",
    name: "Civitai",
    description: "The primary community and repository for Stable Diffusion models and resources.",
    link: "https://civitai.com",
    category: "DALL-E",
    type: "Platform",
    featured: false,
  },
  {
    id: "295",
    name: "Veed.io AI",
    description: "Online video editor with automated subtitles, translations, and AI cleanup.",
    link: "https://veed.io",
    category: "Video",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "296",
    name: "Rask.ai",
    description: "AI tool for dubbing videos into multiple languages with voice cloning.",
    link: "https://rask.ai",
    category: "Video",
    type: "AI Tool",
    featured: true,
  },
  {
    id: "297",
    name: "Pebblely",
    description: "AI product photography that places your items in beautiful professional scenes.",
    link: "https://pebblely.com",
    category: "DALL-E",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "298",
    name: "Flair.ai",
    description: "AI design tool for branded content and beautiful product compositions.",
    link: "https://flair.ai",
    category: "DALL-E",
    type: "AI Tool",
    featured: false,
  },
  {
    id: "299",
    name: "WatermarkRemover.ai",
    description: "Simple AI utility to remove watermarks from images automatically.",
    link: "https://watermarkremover.ai",
    category: "Lifestyle",
    type: "Utility",
    featured: false,
  },
  {
    id: "300",
    name: "Upscale.media",
    description: "AI-powered image enhancement and resolution upscaler.",
    link: "https://upscale.media",
    category: "Lifestyle",
    type: "Utility",
    featured: false,
  },
  {
    id: "301",
    name: "Blackbox AI",
    description: "Fastest code generation and search tool for developers across all platforms.",
    link: "https://blackbox.ai",
    category: "Programming",
    type: "AI Tool",
    featured: true,
  },
]

export const getToolById = (id: string): Tool | undefined => {
  return tools.find((tool) => tool.id === id)
}

export const getToolsByCategory = (category: string): Tool[] => {
  return tools.filter((tool) => tool.category === category)
}

export const getFeaturedTools = (): Tool[] => {
  return tools.filter((tool) => tool.featured)
}

export const getAllCategories = (): string[] => {
  const categories = new Set<string>()
  tools.forEach((tool) => {
    if (tool.category) {
      categories.add(tool.category)
    }
  })
  return Array.from(categories)
}

export const getAllUseCases = (): string[] => {
  const useCases = new Set<string>()
  tools.forEach((tool) => {
    if (tool.useCase) {
      useCases.add(tool.useCase)
    }
  })
  return Array.from(useCases)
}

export const getAllIndustries = (): string[] => {
  const industries = new Set<string>()
  tools.forEach((tool) => {
    if (tool.industry) {
      industries.add(tool.industry)
    }
  })
  return Array.from(industries)
}
